# executable files for this directory
OBJECTS = compounddecls.exe convs.exe dbl_ptr.exe \
		  decl-ex.exe escape.exe inits.exe \
		  literals.exe ref-ex.exe Sales_data.exe \
		  scope_levels.exe unsigned.exe

# tells make to use the file "..\MS_makefile_template", which
# defines general rules for making .obj and .exe files
include ..\MS_makefile_template

LOCFLAGS = -I..\1
