# executable files for this directory
OBJECTS = add.exe add_item.exe add_item2.exe avg_price.exe \
		  for_ex.exe forcount.exe item_io.exe main_only.exe \
		  mysum.exe occurs.exe whilecount.exe \

# tells make to use the file "..\MS_makefile_template", which
# defines general rules for making .obj and .exe files
include ..\MS_makefile_template

add_item.obj add_item2.obj avg_price.obj item_io.obj: Sales_item.h
